### ISSUE TITLE
Dashboard mixes data from different prometheus jobs

### ISSUE THREAD

**Issue by lukaszsamson** [GuillaumeMiralles/prysm-grafana-dashboard#19]
In our setup we have mainnet and testnet validators monitored by one prometheus instance.
Prometheus config includes jobs for testnet and mainnet nodes
```
  - job_name: 'testnet eth2 validator'
    static_configs:
      - targets: ['redacted']
  - job_name: 'testnet eth2 beacon node'
    static_configs:
      - targets: ['redacted']
  - job_name: 'mainnet eth2 validator'
    static_configs:
      - targets: ['redacted']
  - job_name: 'mainnet eth2 beacon node'
    static_configs:
      - targets: ['redacted']
```
The dashboards from this repo mix data from mainnet and testnet. Setting dashboard variables `validator_job` to `mainnet eth2 validator` and `node_job` to `mainnet eth2 beacon node` does not work.
