### ISSUE TITLE
is node_exporter required? 

### ISSUE THREAD

**Issue by koala345** [GuillaumeMiralles/prysm-grafana-dashboard#7]
I originally came to your project from here: 
https://medium.com/@SomerEsat/guide-to-staking-on-ethereum-2-0-ubuntu-prysm-witti-2b972e697918
but noticed an inconsistency with the readme for your dashboard. 

Somer's tutorial includes instructions for installing and running node_exporter, and it's prometheus configuration included this scrape config: 

```
 - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
```
However your readme and example Prometheus config makes no mention of node_exporter. 
Does your dashboard use the node_exporter metrics at all? 

Also, how is your dashboard different from the dashboard linked in the prylabs docs? 
https://docs.prylabs.network/docs/prysm-usage/monitoring/grafana-dashboard/

thanks
